[package]
name = "rust-mp3"
version = "0.1.0"
authors = ["Gijs Molenaar <gijs@pythonic.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "2.0"
