[package]
name = "rust-mp3"
version = "0.1.0"
authors = ["Gijs Molenaar <gijsmolenaar@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "2.0"
num_enum = "0.7.1"
